# Site settings
timezone: Etc/UTC
title: Philihp Busby Blog Posts
email: philihp@gmail.com
description: >-
  Via the mind and mechanism of Philihp Busby.

# Don't set this to /blog, because then the /assets will move into that
baseurl: "/"

url: "https://www.philihp.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title:output_ext

theme: minima

# minima configuration
twitter_username: philihp
github_username: philihp
facebook_username: philihp
instagram_username: philihp
linkedin_username: philihp
keybase_username: philihp
minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: philihp
    github: philihp
    facebook: philihp
    instagram: philihp
    linkedin: philihp
    keybase: philihp

plugins:
  - jekyll-feed
  - jekyll-pgp-signatures
  # put sitemap _AFTER_ all of the URLs you want to generate have been made
  - jekyll-sitemap
  - jekyll-redirect-from

header_pages:
  - about.md
  - pgp.md
  - lightning.md
include: [".well-known"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - _posts/*.asc

author:
  email: philihp@gmail.com
  name: philihp

twitter:
  username: philihp
social:
  name: Philihp Busby
  links:
    - https://twitter.com/philihp
    - https://github.com/philihp
    - https://facebook.com/philihp
    - https://instagram.com/philihp
    - https://linkedin.com/in/philihp
    - https://keybase.io/philihp
