# Site settings
title: philihp.com
email: philihp@gmail.com
description: >-
  From the mind and mechanism of Philihp Busby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philihp.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: philihp
github_username: philihp
minima:
  date_format: "%Y-%m-%d"
disqus:
  shortname: philihp

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - about.md
  - pgp.md
