# Site settings
title: Philihp Busby Blog Posts
email: philihp@gmail.com
description: >-
  From the mind and mechanism of Philihp Busby.
url: "https://philihp.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title:output_ext

twitter_username: philihp
github_username: philihp
facebook_username: philihp
instagram_username: philihp
linkedin_username: philihp
google_analytics: UA-27506789-1

minima:
  date_format: "%Y-%m-%d"

markdown: kramdown
# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - about.md
  - pgp.md
include: [".well-known"]
